services:
    app:
        env_file:
            - .env
        build:
            context: .
            args:
            - CONFIG_ENV=.env
        image: notes-app:0.1
        container_name: app
        ports:
            - ${APP_HTTP_PORT}:8080
        depends_on:
            - pg-storage

    pg-storage:
        env_file:
            - .env
        image: postgres:16.2-alpine
        container_name: pg-storage
        environment:
            POSTGRES_DB: ${APP_DB_DATABASE}
            POSTGRES_USER: ${APP_DB_USER}
            POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./localdata/pg-storage:/var/lib/postgresql/data
        ports:
            - ${APP_DB_PORT}:5432
    