// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notes

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Name   string      `db:"name" json:"name"`
	Text   string      `db:"text" json:"text"`
}

type User struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	Password string      `db:"password" json:"password"`
}
