// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package notes

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	DeleteNoteById(ctx context.Context, id pgtype.UUID) error
	GetAllNotes(ctx context.Context) ([]*Note, error)
	GetAllUsers(ctx context.Context) ([]*User, error)
	GetNote(ctx context.Context, id pgtype.UUID) (*Note, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserByName(ctx context.Context, name string) (*User, error)
	GetUserNoteByName(ctx context.Context, arg GetUserNoteByNameParams) (*Note, error)
	GetUserNotes(ctx context.Context, userID pgtype.UUID) ([]*Note, error)
	UpdateUserNoteByName(ctx context.Context, arg UpdateUserNoteByNameParams) error
}

var _ Querier = (*Queries)(nil)
