name: tests

on:
  push:
    branches:
      - m*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22.5

      - name: Check out code
        uses: actions/checkout@v3

      - name: Go mod tidy
        run: go mod tidy

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: .
          version: v1.60

  tests:
    runs-on: ubuntu-latest
        
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22.5

      - name: Check out code
        uses: actions/checkout@v3

      - name: Start services with Docker Compose
        run: docker compose -f docker-compose-ci.yaml up --build --force-recreate

      - name: Unit tests
        run: go test -race -count 100 -timeout=5m ./...
        working-directory: .
